trigger:
  tags:
    include:
    - v*
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - CHANGELOG.md

variables:
  build: $(Build.BuildId)
  ref: $(Build.SourceBranch)
  branch: $(Build.SourceBranchName)
  dp.cli.version: "3.0.0"
  dp.agent.version: "1.18.0"

jobs:
- job: Linux
  pool:
    vmImage: 'Ubuntu-18.04'

  steps:

  - bash: |
      set -e
      ./bootstrap.bash
    displayName: 'Bootstrap'

  - bash: |
      set -e
      cp ./env.sh ./conf/env.sh
      sed -i "s|TT_CLI_VERSION=.*|TT_CLI_VERSION=\"$(dp.cli.version)\"|g" ./conf/env.sh
      ./run.bash install_cli 
    displayName: 'Test: install cli'

  - bash: |
      set -e
      cp ./env.sh ./conf/env.sh
      sed -i "s|TT_AGENT_VERSION=.*|TT_AGENT_VERSION=\"$(dp.agent.version)\"|g" ./conf/env.sh
      sed -i "s|TT_REGISTRATION_TOKEN=.*|TT_REGISTRATION_TOKEN=\"$(agent.registration_token)\"|g" ./conf/env.sh
      sed -i "s|TT_PROJECT=.*|TT_PROJECT=\"$(project)\"|g" ./conf/env.sh
      ./run.bash install_agent 
    displayName: 'Test: install agent'
